{{ if .Values.grafana.serviceAccount.enabled -}}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: {{ .Values.grafana.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
spec:
  name: {{ .Values.grafana.serviceAccount.name }}
  instanceName: {{ .Values.name }}
  role: {{ .Values.grafana.serviceAccount.role | default "Admin" }}
  isDisabled: false
  tokens:
    - name: {{ .Values.grafana.serviceAccount.token.name }}
      secretName: {{ .Values.grafana.serviceAccount.token.secretName }}
{{- end }}
