{{- if .Values.networkpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}-netpol
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.networkpolicy.podSelector }}
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  {{- end }}
  ingress:
  {{- if .Values.networkpolicy.ingress.allowAll }}
  - {}
  {{- else }}
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.namespace }}
  {{- range $namespaces := .Values.networkpolicy.ingress.namespaces | }}
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $namespaces }}
  {{- end }}
  {{- if .Values.networkpolicy.ingress.internal }}
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8 # RFC1918 private network
  {{- end }}
  {{- if .Values.networkpolicy.ingress.internet }}
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0 # Allow internet
        except:
        - 10.0.0.0/8 # RFC1918 private network
  {{- end }}
  {{- end }}
  egress:
  {{- if .Values.networkpolicy.egress.allowAll }}
  - {}
  {{- else }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.namespace }}
  {{- range $namespaces := .Values.networkpolicy.egress.namespaces }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $namespaces }}
  {{- end }}
  {{- if .Values.networkpolicy.egress.internal }}
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8 # RFC1918 private network
  {{- end }}
  {{- if .Values.networkpolicy.egress.internet }}
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0 # Allow internet
        except:
        - 10.0.0.0/8 # RFC1918 private network
  {{- end }}
  {{- end }}
{{- end }}