{{- if .Values.networkpolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}-netpol
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  ingress:
  - {}
  {{- if .Values.networkpolicy.internalOnly.enabled }}
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.15.0/19
  {{- end }}
{{- end }}