{{- if .Values.ingress.enabled -}}
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.name }}.fiora.li
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.ingress.port }}
{{- end }}