name: argo
namespace: argocd
deployment:
  enabled: false
service:
  enabled: false
networkpolicy:
  podSelector: false
  ingress:
    internal: true
  egress:
    allowAll: true
serviceAccount:
  enabled: false
podDisruptionBudget:
  enabled: false