name: argo
namespace: argocd
deployment:
  enabled: false
service:
  enabled: false
ingress:
  enabled: true
  port: 80
  serviceName: argocd-server
networkpolicy:
  podSelector: false
  ingress:
    internal: true
  egress:
    allowAll: true