name: argo
namespace: argocd
deployment:
  enabled: false
service:
  enabled: false
networkpolicy:
  podSelector: false
  ingress:
    internal: true
  egress:
    allowAll: true
serviceAccount:
  enabled: false
podDisruptionBudget:
  enabled: false
configMap:
  enabled: true
  name: argocd-notifications-cm
  value: |-
    # --- Context ---
    context: |
      argocdUrl: http://argo.fiora.li/

    # --- Slack service definition ---
    service.slack: |
      token: $slack-token
      defaultRecipients: [jared-notifications]

    # --- Triggers ---
    trigger.on-sync-succeeded: |
      - when: app.status.operationState.phase in ['Succeeded'] and app.status.sync.status == 'Synced'
        send: [app-sync-succeeded]

    trigger.on-sync-failed: |
      - when: app.status.operationState.phase in ['Failed']
        send: [app-sync-failed]

    trigger.on-deployed: |
      - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
        send: [app-deployed]

    trigger.on-deleted: |
      - when: app.metadata.deletionTimestamp != nil
        send: [app-deleted]

    trigger.on-health-degraded: |
      - when: app.status.health.status == 'Degraded'
        send: [app-health-degraded]

    trigger.on-sync-status-unknown: |
      - when: app.status.sync.status == 'Unknown'
        send: [app-sync-status-unknown]

    trigger.on-sync-status-out-of-sync: |
      - when: app.status.sync.status == 'OutOfSync'
        send: [app-sync-status-out-of-sync]

    # --- Templates ---
    template.app-sync-succeeded: |
      message: |
        :white_check_mark: *{{.app.metadata.name}}* sync succeeded
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#18be52",
            "fields": [
              {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
              {"title": "Health", "value": "{{.app.status.health.status}}", "short": true},
              {"title": "Revision", "value": "{{.app.status.sync.revision}}", "short": true},
              {"title": "Repository", "value": "{{.app.spec.source.repoURL}}", "short": false}
            ]
          }]

    template.app-sync-failed: |
      message: |
        :x: *{{.app.metadata.name}}* sync failed
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#E96D76",
            "fields": [
              {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
              {"title": "Health", "value": "{{.app.status.health.status}}", "short": true},
              {"title": "Revision", "value": "{{.app.status.sync.revision}}", "short": true},
              {"title": "Repository", "value": "{{.app.spec.source.repoURL}}", "short": false}
            ]
          }]

    template.app-deployed: |
      message: |
        :rocket: *{{.app.metadata.name}}* successfully deployed
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#4BB543",
            "fields": [
              {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
              {"title": "Health", "value": "{{.app.status.health.status}}", "short": true},
              {"title": "Revision", "value": "{{.app.status.sync.revision}}", "short": true},
              {"title": "Repository", "value": "{{.app.spec.source.repoURL}}", "short": false}
            ]
          }]

    template.app-deleted: |
      message: |
        :wastebasket: *{{.app.metadata.name}}* was deleted
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "color": "#AAAAAA",
            "fields": [
              {"title": "Project", "value": "{{.app.spec.project}}", "short": true}
            ]
          }]

    template.app-health-degraded: |
      message: |
        :warning: *{{.app.metadata.name}}* health degraded
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#FFA500",
            "fields": [
              {"title": "Health", "value": "{{.app.status.health.status}}", "short": true},
              {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
              {"title": "Revision", "value": "{{.app.status.sync.revision}}", "short": true}
            ]
          }]

    template.app-sync-status-unknown: |
      message: |
        :grey_question: *{{.app.metadata.name}}* sync status unknown
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "color": "#808080",
            "fields": [
              {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
              {"title": "Revision", "value": "{{.app.status.sync.revision}}", "short": true}
            ]
          }]

    template.app-sync-status-out-of-sync: |
      message: |
        :arrows_counterclockwise: *{{.app.metadata.name}}* is out of sync
      slack:
        attachments: |
          [{
            "title": "{{.app.metadata.name}}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#FFD700",
            "fields": [
              {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
              {"title": "Health", "value": "{{.app.status.health.status}}", "short": true},
              {"title": "Repository", "value": "{{.app.spec.source.repoURL}}", "short": false}
            ]
          }]
