name: emulatorjs
namespace: emulatorjs
deployment:
  enabled: true
podAnnotations:
  diun.enable: "true"
image:
  repository: linuxserver/emulatorjs
  tag: latest@sha256:6ec591b31c0ccb7f6b806aec27f13c936e3fdadb678dca8ee5c179e19f9dc62a
containerPorts:
- containerPort: 80
  name: emulatorjs
  protocol: TCP
- containerPort: 3000
  name: management
  protocol: TCP
resources:
  limits:
    cpu: '2'
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi
probes:
  httpGet:
    path: /
    port: 3000
podSecurityContext: {}
securityContext: {}
service:
  enabled: true
  ports:
  - name: emulatorjs
    port: 80
    protocol: TCP
    targetPort: 80
  - name: management
    port: 3000
    protocol: TCP
    targetPort: 3000
env:
- name: DISABLE_IPFS
  value: "true"
ingress:
  enabled: true
  port: 80
volumeMounts:
- name: config
  mountPath: /config
- name: roms
  mountPath: /data
volumes:
- name: config
  persistentVolumeClaim:
    claimName: emulatorjs
- name: roms
  persistentVolumeClaim:
    claimName: roms
nodeSelector: {}
tolerations: []
affinity: {}
