name: emulatorjs
namespace: emulatorjs
podAnnotations:
  diun.enable: "true"
image:
  repository: ghcr.io/linuxserver/emulatorjs
  tag: latest@sha256:5a19e02c49dc8464c667044ff0ca0bf3a864aac7ed373683c9ab0e5d00388819
containerPorts:
- containerPort: 80
  name: emulatorjs
  protocol: TCP
- containerPort: 3000
  name: management
  protocol: TCP
resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi
startupProbe:
  httpGet:
    path: /
    port: 3000
livenessProbe:
  httpGet:
    path: /
    port: 3000
readinessProbe:
  httpGet:
    path: /
    port: 3000
podSecurityContext: {}
securityContext: {}
service:
  ports:
  - name: emulatorjs
    port: 80
    protocol: TCP
    targetPort: 80
  - name: management
    port: 3000
    protocol: TCP
    targetPort: 3000
env:
  - name: DISABLE_IPFS
    value: "true"
ingress:
  enabled: true
  port: 80
volumeMounts:
- name: config
  mountPath: /config
- name: roms
  mountPath: /data
volumes:
- name: config
  persistentVolumeClaim:
    claimName: emulatorjs
- name: roms
  persistentVolumeClaim:
    claimName: roms
nodeSelector: {}
tolerations: []
affinity: {}
