name: emulatorjs
namespace: emulatorjs
deployment:
  enabled: true
image:
  repository: linuxserver/emulatorjs
  tag: latest@sha256:07d00a775452ec9a939014e878b16115a79811434d134a4151e075fc39b3c860
containerPorts:
- containerPort: 80
  name: emulatorjs
  protocol: TCP
- containerPort: 3000
  name: management
  protocol: TCP
resources:
  limits:
    cpu: '1'
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi
probes:
  httpGet:
    path: /
    port: 3000
podSecurityContext: {}
securityContext: {}
service:
  enabled: true
  ports:
  - name: emulatorjs
    port: 80
    protocol: TCP
    targetPort: 80
  - name: management
    port: 3000
    protocol: TCP
    targetPort: 3000
env:
- name: DISABLE_IPFS
  value: "true"
ingress:
  enabled: true
  port: 80
volumeMounts:
- name: config
  mountPath: /config
- name: roms
  mountPath: /data
volumes:
- name: config
  persistentVolumeClaim:
    claimName: emulatorjs
- name: roms
  persistentVolumeClaim:
    claimName: roms
nodeSelector: {}
tolerations: []
affinity: {}
networkpolicy:
  ingress:
    internal: true
