name: emulatorjs
namespace: emulatorjs
deployment:
  enabled: true
image:
  repository: docker.io/linuxserver/emulatorjs
  tag: latest@sha256:bc892148cee315125f48640f5a2b7ca6bd599967574424d71060c064e8a36a48
containerPorts:
- containerPort: 80
  name: emulatorjs
  protocol: TCP
- containerPort: 3000
  name: management
  protocol: TCP
resources:
  limits:
    cpu: '1'
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi
probes:
  httpGet:
    path: /
    port: management
service:
  enabled: true
  ports:
  - name: emulatorjs
    port: 80
    protocol: TCP
    targetPort: emulatorjs
  - name: management
    port: 3000
    protocol: TCP
    targetPort: management
env:
- name: DISABLE_IPFS
  value: "true"
- name: S6_READ_ONLY_ROOT
  value: "1"
- name: S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES
  value: "1"
ingress:
  enabled: true
volumeMounts:
- name: emulatorjs-configmap
  mountPath: /config/profile/default/retroarch.cfg
  subPath: retroarch.cfg
  readOnly: true
- name: roms
  mountPath: /data
volumes:
- name: emulatorjs-configmap
  configMap:
    name: emulatorjs-configmap
    defaultMode: 511
- name: roms
  persistentVolumeClaim:
    claimName: roms
nodeSelector: {}
tolerations: []
affinity: {}
networkpolicy:
  ingress:
    internal: true
# Outstanding bug with s6: https://github.com/just-containers/s6-overlay/issues/600
# containerSecurityContext:
#   allowPrivilegeEscalation: false
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   privileged: false
# podSecurityContext:
#   fsGroup: 2000
#   runAsNonRoot: true
#   runAsUser: 1000
configMap:
  enabled: true
  value: |
    retroarch.cfg: |
      input_menu_toggle_gamepad_combo = 3
      system_directory = /home/web_user/retroarch/system/
