name: emulatorjs
namespace: emulatorjs
deployment:
  enabled: true
image:
  repository: docker.io/linuxserver/emulatorjs
  tag: latest@sha256:66a1d3fb26ccbbbc0b670ef87b72365eff29a9b8603557e9b5df5adf3d9f82a8
containerPorts:
- containerPort: 80
  name: emulatorjs
  protocol: TCP
- containerPort: 3000
  name: management
  protocol: TCP
resources:
  limits:
    cpu: '1'
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi
probes:
  httpGet:
    path: /
    port: management
containerSecurityContext: {}
podSecurityContext: {}
service:
  enabled: true
  ports:
  - name: emulatorjs
    port: 80
    protocol: TCP
    targetPort: emulatorjs
  - name: management
    port: 3000
    protocol: TCP
    targetPort: management
env:
- name: DISABLE_IPFS
  value: "true"
- name: S6_READ_ONLY_ROOT
  value: "1"
- name: S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES
  value: "1"
ingress:
  enabled: true
volumeMounts:
- name: config
  mountPath: /config
- name: roms
  mountPath: /data
volumes:
- name: config
  persistentVolumeClaim:
    claimName: emulatorjs
- name: roms
  persistentVolumeClaim:
    claimName: roms
nodeSelector: {}
tolerations: []
affinity: {}
networkpolicy:
  ingress:
    internal: true
