name: emulatorjs
namespace: emulatorjs
deployment:
  enabled: true
image:
  repository: linuxserver/emulatorjs
  tag: latest@sha256:3072e31fc44633120dce2b60a2bdfc4150d69b978bd794f756093f1699a81eba
containerPorts:
- containerPort: 80
  name: emulatorjs
  protocol: TCP
- containerPort: 3000
  name: management
  protocol: TCP
resources:
  limits:
    cpu: '1'
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi
probes:
  httpGet:
    path: /
    port: management
podSecurityContext: {}
securityContext: {}
service:
  enabled: true
  ports:
  - name: emulatorjs
    port: 80
    protocol: TCP
    targetPort: emulatorjs
  - name: management
    port: 3000
    protocol: TCP
    targetPort: 3000
env:
- name: DISABLE_IPFS
  value: "true"
ingress:
  enabled: true
  name: emulatorjs
volumeMounts:
- name: config
  mountPath: /config
- name: roms
  mountPath: /data
volumes:
- name: config
  persistentVolumeClaim:
    claimName: emulatorjs
- name: roms
  persistentVolumeClaim:
    claimName: roms
nodeSelector: {}
tolerations: []
affinity: {}
networkpolicy:
  ingress:
    internal: true
