name: grafana
namespace: monitoring
deployment:
  enabled: true
replicaCount: 1
strategyType: RollingUpdate
image:
  repository: docker.io/grafana/grafana-oss
  tag: latest@sha256:e932bd6ed0e026595b08483cd0141e5103e1ab7ff8604839ff899b8dc54cabcb
containerPorts:
- containerPort: 3000
  name: grafana
  protocol: TCP
resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi
probes:
  httpGet:
    path: /api/health
    port: grafana
  startupProbe:
    failureThreshold: 15
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 120
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 3
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 5
podLabels:
  app.kubernetes.io/name: grafana
service:
  enabled: true
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: grafana
env:
- name: GF_FEATURE_TOGGLES_ENABLE
  value: "provisioning,kubernetesDashboards"
- name: GF_ALERTING_ENABLED
  value: "false"
- name: GF_ALERTING_EXECUTE_ALERTS_ENABLED
  value: "false"
- name: GF_ALERTING_MIN_INTERVAL_SECONDS
  value: "86400"
- name: GF_CLOUD_MIGRATION_ENABLED
  value: "false"
- name: GF_UNIFIED_ALERTING_ENABLED
  value: "false"
- name: GF_AUTH_DISABLE_LOGIN_FORM
  value: "false"
- name: GF_PLUGINS_CHECK_FOR_UPDATES
  value: "false"
- name: GF_PLUGIN_ADMIN_ENABLED
  value: "false"
- name: GF_LIVE_ENABLED
  value: "false"
- name: GF_PUBLIC_DASHBOARDS_ENABLED
  value: "false"
- name: GF_ANALYTICS_ENABLED
  value: "false"
- name: GF_ANALYTICS_REPORTING_ENABLED
  value: "false"
- name: GF_RECORDED_QUERIES_ENABLED
  value: "false"
- name: GF_RECORDING_RULES_ENABLED
  value: "false"
- name: GF_REPORTING_ENABLED
  value: "false"
- name: GF_SUPPORT_BUNDLES_ENABLED
  value: "false"
- name: GF_METRICS_ENABLED
  value: "false"
- name: GF_AUTHORIZATION_CACHE_TTL
  value: "86400s"
- name: GF_DASHBOARD_CLEANUP_INTERVAL
  value: "86400s"
- name: GF_ANALYTICS_CHECK_FOR_UPDATES
  value: "false"
- name: GF_NEWS_NEWS_FEED_ENABLED
  value: "false"
- name: GF_SNAPSHOTS_ENABLED
  value: "false"
- name: GF_DASHBOARDS_MIN_REFRESH_INTERVAL
  value: 15m
- name: GF_QUERY_CACHE_ENABLED
  value: "true"
- name: GF_QUERY_CACHE_TYPE
  value: "memory"
- name: GF_QUERY_CACHE_TTL
  value: "5m"
- name: GF_UNIFIED_STORAGE_INDEX_MIN_UPDATE_INTERVAL
  value: "30s"
- name: GF_UNIFIED_STORAGE_ENABLE_SEARCH
  value: "false"
- name: GF_UNIFIED_STORAGE_INDEX_WORKERS
  value: "2"
- name: GF_UNIFIED_STORAGE_OVERRIDES_RELOAD_PERIOD
  value: "120s"
- name: GF_DATABASE_HIGH_AVAILABILITY
  value: "false"
- name: GF_DATABASE_TYPE
  valueFrom:
    secretKeyRef:
      name: grafana-postgres-credentials
      key: DB_TYPE
- name: GF_DATABASE_NAME
  valueFrom:
    secretKeyRef:
      name: grafana-postgres-credentials
      key: DB_NAME
- name: GF_DATABASE_PORT
  valueFrom:
    secretKeyRef:
      name: grafana-postgres-credentials
      key: DB_PORT
- name: GF_DATABASE_USER
  valueFrom:
    secretKeyRef:
      name: grafana-postgres-credentials
      key: DB_USERNAME
- name: GF_DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: grafana-postgres-credentials
      key: DB_PASSWORD
- name: GF_DATABASE_HOST
  valueFrom:
    secretKeyRef:
      name: grafana-postgres-credentials
      key: DB_HOST
- name: GF_DATABASE_SSL_MODE
  value: require
ingress:
  enabled: true
volumeMounts:
- name: grafana-storage
  mountPath: /var/lib/grafana
- name: tmp
  mountPath: /tmp
volumes:
- name: grafana-storage
  emptyDir: {}
- name: tmp
  emptyDir: {}
networkpolicy:
  ingress:
    internal: true
  egress:
    internet: true
    namespaces:
    - monitoring
    - loki
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  privileged: false
podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
imageUpdater:
  enabled: true
externalSecrets:
- name: grafana-postgres-credentials
  data:
  - secretKey: DB_TYPE
    remoteRef:
      key: /homelab/grafana/DB_TYPE
  - secretKey: DB_NAME
    remoteRef:
      key: /homelab/grafana/DB_NAME
  - secretKey: DB_PORT
    remoteRef:
      key: /homelab/grafana/DB_PORT
  - secretKey: DB_USERNAME
    remoteRef:
      key: /homelab/grafana/DB_USERNAME
  - secretKey: DB_PASSWORD
    remoteRef:
      key: /homelab/grafana/DB_PASSWORD
  - secretKey: DB_HOST
    remoteRef:
      key: /homelab/grafana/DB_HOST
prometheusRules:
  enabled: true
  rules:
  - alert: SupabaseIngressBandwidthWarning
    annotations:
      description: The supabase ingress usage for {{$labels.Project}} has exceeded 2K bits for more than 5 minutes
      summary: The rate of bandwidth usage for supabase is over 2K
    expr: (rate(supavisor_client_network_recv[5m])) > 2000
    for: 5m
    labels:
      issue: Supabase ingress usage for {{$labels.Project}} is too high
      severity: critical
