name: headlamp
namespace: kube-system
deployment:
  enabled: false
service:
  enabled: false
ingress:
  enabled: true
  name: headlamp
  portName: http
networkpolicy:
  podSelector: true
  ingress:
    allowAll: false
    internal: false
    network: false
    internet: false
  egress:
    allowAll: false
    internal: false
    network: false
    internet: false
