name: homepage
namespace: homepage
deployment:
  enabled: true
image:
  repository: ghcr.io/gethomepage/homepage
  tag: latest@sha256:5e6bcbb595c4e857540577135e0f8b3ffc2e97c23d6e0ddc7df183de5bfdd442
containerPorts:
- containerPort: 3000
  name: homepage
  protocol: TCP
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi
probes:
  httpGet:
    path: /
    port: homepage
podLabels:
  app.kubernetes.io/name: homepage
service:
  enabled: true
  ports:
  - name: homepage
    port: 3000
    protocol: TCP
    targetPort: homepage
env:
- name: HOMEPAGE_ALLOWED_HOSTS
  value: "homepage.fiora.li"
- name: LOG_LEVEL
  value: "debug"
ingress:
  enabled: true
volumeMounts:
- mountPath: /app/config/custom.js
  name: homepage-configmap
  subPath: custom.js
  readOnly: true
- mountPath: /app/config/custom.css
  name: homepage-configmap
  subPath: custom.css
  readOnly: true
- mountPath: /app/config/bookmarks.yaml
  name: homepage-configmap
  subPath: bookmarks.yaml
  readOnly: true
- mountPath: /app/config/docker.yaml
  name: homepage-configmap
  subPath: docker.yaml
  readOnly: true
- mountPath: /app/config/kubernetes.yaml
  name: homepage-configmap
  subPath: kubernetes.yaml
  readOnly: true
- mountPath: /app/config/services.yaml
  name: homepage-configmap
  subPath: services.yaml
  readOnly: true
- mountPath: /app/config/settings.yaml
  name: homepage-configmap
  subPath: settings.yaml
  readOnly: true
- mountPath: /app/config/widgets.yaml
  name: homepage-configmap
  subPath: widgets.yaml
  readOnly: true
- mountPath: /app/config/logs
  name: logs
volumes:
- name: homepage-configmap
  configMap:
    name: homepage-configmap
- name: logs
  emptyDir: {}
nodeSelector: {}
tolerations: []
affinity: {}
networkpolicy:
  ingress:
    internal: true
  egress:
    internal: true
    network: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  privileged: false
podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
clusterRoleBinding:
  enabled: true
clusterRole:
  enabled: true
  rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - gateways
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
configMap:
  enabled: true
  name: homepage-configmap
  data:
    kubernetes.yaml: |
      mode: cluster
    settings.yaml: |
      providers:
        longhorn:
          url: http://longhorn.fiora.li
    custom.css: ""
    custom.js: ""
    bookmarks.yaml: |
      - Developer:
        - Github:
          - abbr: GH
            href: https://github.com/
    services.yaml: |
      - My First Group:
          - My First Service:
              href: http://localhost/
              description: Homepage is awesome
      - My Second Group:
          - My Second Service:
              href: http://localhost/
              description: Homepage is the best
      - My Third Group:
          - My Third Service:
              href: http://localhost/
              description: Homepage is 😎
    widgets.yaml: |
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - resources:
          backend: resources
          expanded: true
          cpu: true
          memory: true
          network: default
      - search:
          provider: duckduckgo
          target: _blank
    docker.yaml: ""