name: kromgo
namespace: monitoring
deployment:
  enabled: true
strategyType: RollingUpdate
image:
  repository: ghcr.io/kashalls/kromgo
  tag: latest@sha256:4b908ea0be5acd61e67ce38d8f1342d0731296b00b8ca2c35533aa519d804cc6
containerPorts:
- containerPort: 8080
  name: kromgo
  protocol: TCP
- containerPort: 8888
  name: healthz
  protocol: TCP
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi
probes:
  httpGet:
    path: /healthz
    port: healthz
service:
  enabled: true
  ports:
  - name: kromgo
    port: 8080
    protocol: TCP
    targetPort: kromgo
env:
- name: PROMETHEUS_URL
  value: "http://prometheus-kube-prometheus-prometheus:9090"
ingress:
  enabled: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  privileged: false
podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
networkpolicy:
  ingress:
    internal: true
volumeMounts:
- name: kromgo-configmap
  mountPath: /kromgo/config.yaml
  subPath: config.yaml
  readOnly: true
volumes:
- name: kromgo-configmap
  configMap:
    name: kromgo-configmap
    defaultMode: 511
configMap:
  enabled: true
  data:
  name: config.yaml
  value: |-
    ---
    # yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
    badge:
      font: Verdana.ttf # Relative to /kromgo - Verdana.ttf is available in the container
      size: 12
    metrics:
      # - name: longhorn_volume_state
      #   query: longhorn_volume_state{}
      #   colors:
      #     - { valueOverride: 'Healthy', color: "green", min: 2, max: 2 }
      #     - { valueOverride: 'Degraded', color: "red", min: 0, max: 1 }
      #     - { valueOverride: 'Unmounted', color: "orange", min: 3, max: 3 }
      - name: kubernetes_version
        query: kubernetes_build_info{service="kubernetes"}
        label: git_version
      - name: argocd_version
        query: argocd_info{}
        label: version

      - name: cluster_uptime_days
        query: ceil(avg(node_time_seconds - node_boot_time_seconds)/60/60/24)
        prefix: ""
        suffix: "d"
        colors:
          - color: "green"
            min: 0
            max: 100
      - name: cluster_node_count
        query: count(count by (node) (kube_node_info))
        colors:
          - color: "green"
            min: 0
            max: 100
      - name: cluster_pod_count
        query: sum(kube_pod_status_phase{phase="Running"})
        colors:
          - color: "green"
            min: 0
            max: 1000
      - name: cluster_cpu_usage
        query: "round(cluster:node_cpu:ratio_rate5m * 100, 0.1)"
        prefix: ""
        suffix: "%"
        colors:
          - color: "green"
            min: 0
            max: 50
          - color: "orange"
            min: 51
            max: 75
          - color: "red"
            min: 76
            max: 1000
      - name: cluster_memory_usage
        query: "round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)*100, 0.1)"
        prefix: ""
        suffix: "%"
        colors:
          - color: "green"
            min: 0
            max: 50
          - color: "orange"
            min: 51
            max: 75
          - color: "red"
            min: 76
            max: 1000
      - name: cluster_power_usage
        query: unpoller_device_outlet_ac_power_consumption{}
        prefix: ""
        suffix: "W"
        colors:
        - color: "green"
          min: 0
          max: 230
        - color: "red"
          min: 231
          max: 1000
      - name: cluster_popeye_score
        query: popeye_report_score{}
        prefix: ""
        suffix: "%"
        colors:
          - color: "red"
            min: 0
            max: 99
          - color: "green"
            min: 100
            max: 1000
