name: kromgo
namespace: monitoring
deployment:
  enabled: true
image:
  repository: ghcr.io/kashalls/kromgo
  tag: latest@sha256:4b908ea0be5acd61e67ce38d8f1342d0731296b00b8ca2c35533aa519d804cc6
containerPorts:
- containerPort: 8080
  name: kromgo
  protocol: TCP
- containerPort: 8888
  name: healthz
  protocol: TCP
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi
probes:
  httpGet:
    path: /healthz
    port: healthz
service:
  enabled: true
  ports:
  - name: kromgo
    port: 8080
    protocol: TCP
    targetPort: kromgo
env:
- name: PROMETHEUS_URL
  value: "http://prometheus-kube-prometheus-prometheus:9090"
ingress:
  enabled: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  privileged: false
podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
networkpolicy:
  ingress:
    internal: true
volumeMounts:
- name: kromgo-configmap
  mountPath: /kromgo/config.yaml
  subPath: config.yaml
  readOnly: true
volumes:
- name: kromgo-configmap
  configMap:
    name: kromgo-configmap
    defaultMode: 511
configMap:
  enabled: true
  data:
  name: config.yaml
  value: |-
    ---
    # yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
    badge:
      font: Verdana.ttf # Relative to /kromgo - Verdana.ttf is available in the container
      size: 12
    metrics:
      - name: node_cpu_usage
        query: "round(cluster:node_cpu:ratio_rate5m * 100, 0.1)"
        prefix: ""      # Optional
        suffix: "%"     # Optional
        colors:         # Optional
          - color: "green"
            min: 0
            max: 50
          - color: "orange"
            min: 51
            max: 75
          - color: "red"
            min: 76
            max: 1000
      - name: node_memory_usage
        query: "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)"
        prefix: ""      # Optional
        suffix: "%"     # Optional
        colors:         # Optional
          - color: "green"
            min: 0
            max: 50
          - color: "orange"
            min: 51
            max: 75
          - color: "red"
            min: 76
            max: 1000
      - name: popeye_report_score
        query: popeye_report_score{}
        prefix: ""      # Optional
        suffix: "%"     # Optional
        colors:         # Optional
          - color: "red"
            min: 0
            max: 99
          - color: "green"
            min: 100
            max: 1000
      - name: longhorn_volume_state
        query: longhorn_volume_state{}
        colors:
          - { valueOverride: 'Healthy', color: "green", min: 2, max: 2 }
          - { valueOverride: 'Degraded', color: "red", min: 0, max: 1 }
          - { valueOverride: 'Unmounted', color: "orange", min: 3, max: 3 }
      - name: kubernetes_build_version
        query: kubernetes_build_info{service="kubernetes"}
        label: git_version
      - name: argocd_info
        query: argocd_info{}
        label: version