name: nut
namespace: nut
deployment:
  enabled: true
strategyType: RollingUpdate
image:
  repository: shawly/nut:latest
  tag: latest@sha256:5145c737fba38cd597c93a45b63ce72c368b6fb50da4ca8ae84be1ee6d7fec40
containerPorts:
- containerPort: 9000
  name: http
  protocol: TCP
resources:
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 250m
    memory: 100Mi
probes:
  tcpSocket:
    port: http
service:
  enabled: true
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
networkpolicy:
  ingress:
    internal: true
  egress:
    internet: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  privileged: false
podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
