name: pinchflat
namespace: downloader
deployment:
  enabled: true
image:
  repository: docker.io/keglin/pinchflat
  tag: latest@sha256:06e20be2ad935f1ee2b527f99d1492086d7b82713739abf016e46632992079ec
containerPorts:
- containerPort: 8945
  name: pinchflat
  protocol: TCP
resources:
  limits:
    cpu: '2'
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi
probes:
  httpGet:
    path: /healthcheck
    port: pinchflat
service:
  enabled: true
  ports:
  - name: pinchflat
    port: 8945
    protocol: TCP
    targetPort: pinchflat
env:
- name: TZ
  value: "America/Toronto"
- name: LOG_LEVEL
  value: "info"
- name: ENABLE_PROMETHEUS
  value: "true"
- name: TMPDIR
  value: "/tmp"
ingress:
  enabled: true
volumeMounts:
- name: pinchflat-persistent-storage
  mountPath: /config
- name: media-youtube
  mountPath: /downloads
- name: tmp
  mountPath: /tmp
- name: yt-dlp
  mountPath: /etc/yt-dlp
volumes:
- name: pinchflat-persistent-storage
  persistentVolumeClaim:
    claimName: pinchflat
- name: media-youtube
  persistentVolumeClaim:
    claimName: media-youtube
- name: tmp
  emptyDir: {}
- name: yt-dlp
  emptyDir: {}
nodeSelector: {}
tolerations: []
affinity: {}
networkpolicy:
  ingress:
    internal: true
  egress:
    internet: true
podSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  privileged: false
securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
