name: promobee
namespace: monitoring
deployment:
  enabled: true
podAnnotations:
  diun.enable: "true"
image:
  repository: jaredfiorali/promobee:v1
  tag: v1@sha256:06e20be2ad935f1ee2b527f99d1492086d7b82713739abf016e46632992079ec
containerPorts:
- containerPort: 8080
  name: promobee
  protocol: TCP
resources:
  limits:
    cpu: 250m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi
probes:
  httpGet:
    path: /
    port: 8080
service:
  enabled: true
  ports:
  - name: promobee
    port: 8080
    protocol: TCP
    targetPort: 8080
command:
  enabled: true
  exec: ["/bin/sh", "-c", "mkdir -p /opt/promobee && cp /tmp/promobee.store /opt/promobee/promobee.store && ./promobee"]
env:
- name: PROMOBEE_API_KEY
  valueFrom:
    secretKeyRef:
      name: promobee-credentials
      key: api-key
- name: PROMOBEE_PORT
  value: "8080"
- name: PROMOBEE_TOKEN_STORE
  value: "/opt/promobee/promobee.store"
volumeMounts:
- name: store
  mountPath: /tmp/promobee.store
  subPath: store
  readOnly: true
volumes:
- name: store
  secret:
    secretName: promobee-store
