name: promobee
namespace: monitoring
deployment:
  enabled: true
podAnnotations:
  diun.enable: "true"
image:
  repository: jaredfiorali/promobee
  tag: v1@sha256:ec4a2de97943cc8265e13747fc66563be55696622f05d44bc0a1d2b16b25b623
containerPorts:
- containerPort: 8080
  name: promobee
  protocol: TCP
resources:
  limits:
    cpu: 250m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi
probes:
  tcpSocket:
    port: 8080
service:
  enabled: true
  ports:
  - name: promobee
    port: 8080
    protocol: TCP
    targetPort: 8080
command:
  enabled: true
  exec: ["/bin/sh", "-c", "mkdir -p /opt/promobee && cp /tmp/promobee.store /opt/promobee/promobee.store && ./promobee"]
env:
- name: PROMOBEE_API_KEY
  valueFrom:
    secretKeyRef:
      name: promobee-credentials
      key: api-key
- name: PROMOBEE_PORT
  value: "8080"
- name: PROMOBEE_TOKEN_STORE
  value: "/opt/promobee/promobee.store"
volumeMounts:
- name: store
  mountPath: /tmp/promobee.store
  subPath: store
  readOnly: true
volumes:
- name: store
  secret:
    secretName: promobee-store
networkpolicy:
  egress:
    internal: false
    internet: true
