name: ssh
namespace: ssh
deployment:
  enabled: true
image:
  repository: ghcr.io/linuxserver/openssh-server
  tag: latest@sha256:b8497525b4ef1931bbf04e05e97901fc2a4689736dc2fcbda47cba90a8f8f70c
containerPorts:
- containerPort: 2222
  name: ssh
  protocol: TCP
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500Mi
probes:
  tcpSocket:
    port: ssh
service:
  enabled: true
  ports:
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: ssh
  externalTrafficPolicy: Local
  type: LoadBalancer
env:
- name: PUID
  value: "1000"
- name: PGID
  value: "1000"
- name: TZ
  value: "America/Toronto"
- name: PUBLIC_KEY
  valueFrom:
    secretKeyRef:
      name: ssh-credentials
      key: public-key
- name: SUDO_ACCESS
  value: "false"
- name: PASSWORD_ACCESS
  value: "false"
- name: USER_NAME
  value: "rameez"
- name: LOG_STDOUT
  value: "true"
ingress:
  enabled: true
volumeMounts:
- name: ssh-storage
  mountPath: /mnt/ssh
volumes:
- name: ssh-storage
  persistentVolumeClaim:
    claimName: ssh
networkpolicy:
  ingress:
    internet: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  privileged: false
podSecurityContext: {}