name: timemachine
namespace: timemachine
deployment:
  enabled: true
image:
  repository: docker.io/mbentley/timemachine
  tag: latest@sha256:3cdf1f5fac4e74e832ff19751bef3dcce7afddbbc5283cf60b84131d2d0220b0
containerPorts:
- containerPort: 137
  name: udp137
  protocol: UDP
- containerPort: 138
  name: udp138
  protocol: UDP
- containerPort: 139
  name: tcp139
- containerPort: 445
  name: tcp445
resources:
  limits:
    cpu: '1'
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1500Mi
probes:
  tcpSocket:
    port: tcp445
service:
  enabled: true
  ports:
  - port: 139
    name: tcp139
    targetPort: tcp139
  - port: 445
    name: tcp445
    targetPort: tcp445
  externalTrafficPolicy: Local
  type: LoadBalancer
env:
- name: ADVERTISED_HOSTNAME
  value: ""
- name: CUSTOM_SMB_CONF
  value: "false"
- name: CUSTOM_USER
  value: "false"
- name: DEBUG_LEVEL
  value: "1"
- name: MIMIC_MODEL
  value: "TimeCapsule8,119"
- name: EXTERNAL_CONF
  value: ""
- name: HIDE_SHARES
  value: "no"
- name: TM_USERNAME
  value: "timemachine"
- name: TM_GROUPNAME
  value: "timemachine"
- name: TM_UID
  value: "817"
- name: TM_GID
  value: "922"
- name: PASSWORD
  value: "timemachine"
- name: SET_PERMISSIONS
  value: "true"
- name: SHARE_NAME
  value: "TimeMachine"
- name: SMB_INHERIT_PERMISSIONS
  value: "no"
- name: SMB_NFS_ACES
  value: "yes"
- name: SMB_METADATA
  value: "stream"
- name: SMB_PORT
  value: "445"
- name: SMB_VFS_OBJECTS
  value: "acl_xattr fruit streams_xattr"
- name: VOLUME_SIZE_LIMIT
  value: "0"
- name: WORKGROUP
  value: "WORKGROUP"
ingress:
  enabled: false
volumeMounts:
- name: timemachine-persistent-storage
  mountPath: /opt/timemachine
volumes:
- name: timemachine-persistent-storage
  persistentVolumeClaim:
    claimName: timemachine
networkpolicy:
  ingress:
    internal: true
volume:
  enabled: true
  size: "214748364800"
  numberOfReplicas: 1
  snapshots:
    daily: false
# Attempted to adjust the security context,
# however the pod does need root permission to be able to add users and update passwords
containerSecurityContext: {}
podSecurityContext: {}
