- name: gluetun
  image: qmcgaw/gluetun@sha256:183c74263a07f4c931979140ac99ff4fbc44dcb1ca5b055856ef580b0fafdf1c
  resources:
    limits:
      cpu: 1500m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 500Mi
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  securityContext:
    privileged: true
    capabilities:
      add:
        - NET_ADMIN
  startupProbe:
    successThreshold: 1
    failureThreshold: 18
    periodSeconds: 10
    timeoutSeconds: 5
    exec:
      command:
        - sh
        - -c
        - wget -q -T 10 -t 2 127.0.0.1:9999 && echo 0 || echo 1
  livenessProbe:
    successThreshold: 1
    failureThreshold: 3
    periodSeconds: 30
    timeoutSeconds: 5
    exec:
      command:
        - sh
        - -c
        - wget -q -T 10 -t 2 127.0.0.1:9999 && echo 0 || echo 1
  readinessProbe:
    successThreshold: 2
    failureThreshold: 2
    periodSeconds: 10
    timeoutSeconds: 5
    exec:
      command:
        - sh
        - -c
        - wget -q -T 10 -t 2 127.0.0.1:9999 && echo 0 || echo 1
  env:
    - name: VPN_SERVICE_PROVIDER
      value: "private internet access"
    - name: OPENVPN_FLAGS
      value: "--fast-io --sndbuf 1024000 --rcvbuf 1024000 --compress"
    - name: OPENVPN_CIPHERS
      value: "aes-128-cbc"
    - name: OPENVPN_USER
      valueFrom:
        secretKeyRef:
          name: pia-credentials
          key: username
    - name: OPENVPN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pia-credentials
          key: password
    - name: SERVER_REGIONS
      value: "CA Toronto"
    - name: PORT_FORWARD_ONLY
      value: "true"
    - name: VPN_PORT_FORWARDING
      value: "on"
    - name: VPN_PORT_FORWARDING_STATUS_FILE
      value: "/gluetun/forwarded_port.txt"
  ports:
    - containerPort: 8000
      name: gluetun
  volumeMounts:
  - name: port-forward
    mountPath: /gluetun
- name: ping
  image: busybox:stable
  command:
  - sh
  - -c
  - |
    while ! ping -c 1 google.com; do
      echo "Ping failed, retrying in 5"
      sleep 5
    done
    echo "ping successful, exiting"
- name: update-peer-port
  image: busybox:stable
  command:
  - sh
  - -c
  - |
    while [ ! -f "/gluetun/forwarded_port.txt" ]; do
      echo "Waiting for port forward..."
      sleep 5
    done
    export FORWARDED_PORT="$(cat /gluetun/forwarded_port.txt)"
    sed -i "s/\"peer-port\":.*/\"peer-port\": $FORWARDED_PORT,/g" /config/settings.json
    echo "transmission port updated to $FORWARDED_PORT"
    cat /config/settings.json
  volumeMounts:
  - name: transmission
    mountPath: /config
  - name: port-forward
    mountPath: /gluetun